# Generated by Django 2.1.10 on 2019-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('pub_date', models.DateField()),
                ('text_body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
